services:
  - type: web
    name: uniceif-music-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: OWNER_ID
        sync: false
      - key: SUDO_USERS
        sync: false
      - key: ACCESS_KEYS
        sync: false
      - key: LOG_GROUP_ID
        sync: false
      - key: DURATION_LIMIT_MIN
        value: "120"
      - key: AUTO_LEAVE_SECONDS
        value: "300"
      - key: DEFAULT_TIER
        value: "free"
      - key: AUDIO_BITRATE
        value: "48k"
      - key: STREAM_QUALITY
        value: "high"
